# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"mlbc_model": "bcml_model.ipynb"}

modules = ["bcml_model.py"]

doc_url = "https://sheride.github.io/bcml4pheno/"

git_url = "https://github.com/sheride/bcml4pheno/tree/master/"

def custom_doc_links(name): return None
