# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"bcml_model": "bcml_model.ipynb",
         "refresh_model": "bcml_model.ipynb",
         "label_predictors": "data_preproc.ipynb",
         "get_settings": "data_vis.ipynb",
         "cross_section_helper": "data_vis.ipynb",
         "multi_model": "multi_model.ipynb",
         "get_elijah_ttbarzp_cs": "ttbarzp.ipynb",
         "get_manuel_ttbarzp_cs": "ttbarzp.ipynb",
         "import47Ddata": "ttbarzp.ipynb",
         "get47Dfeatures": "ttbarzp.ipynb"}

modules = ["bcml_model.py",
           "data_preproc.py",
           "data_vis.py",
           "multi_model.py",
           "ttbarzp.py"]

doc_url = "https://sheride.github.io/bcml4pheno/"

git_url = "https://github.com/sheride/bcml4pheno/tree/master/"

def custom_doc_links(name): return None
