# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"bcml_model": "bcml_model.ipynb",
         "refresh_model": "bcml_model.ipynb",
         "get_settings": "data_vis.ipynb",
         "cross_section_helper": "data_vis.ipynb",
         "manual_significance": "manual_opt.ipynb",
         "points2hrs": "manual_opt.ipynb",
         "maxhrs2points": "manual_opt.ipynb",
         "sig_grid": "manual_opt.ipynb",
         "opt_sig": "manual_opt.ipynb",
         "get_elijah_ttbarzp_cs": "ttbarzp.ipynb",
         "get_manuel_ttbarzp_cs": "ttbarzp.ipynb",
         "import47Ddata": "ttbarzp.ipynb",
         "get47Dfeatures": "ttbarzp.ipynb"}

modules = ["bcml_model.py",
           "data_vis.py",
           "manual_opt.py",
           "ttbarzp.py"]

doc_url = "https://sheride.github.io/bcml4pheno/"

git_url = "https://github.com/sheride/bcml4pheno/tree/master/"

def custom_doc_links(name): return None
